###Testing api calls

###User
###Get New User
GET http://localhost:8001/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzI4NTA2NzUyLCJleHAiOjE3Mjg1OTMxNTJ9.0wPcZEz5G99L_0vry35jluMCjCuwYalNudy4PJQryMo

### login New User
POST http://localhost:8001/api/v1/users/login
Content-Type: application/json

{
    
    "email":"a@gmail.com",
    "password":"as"
}




###Transactions

### Post new Transaction
POST http://localhost:8001/api/v1/transactions
Content-Type:application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzI4NTA2NzUyLCJleHAiOjE3Mjg1OTMxNTJ9.0wPcZEz5G99L_0vry35jluMCjCuwYalNudy4PJQryMo

{
    "type":"income",
    "title":"Salary",
    "amount":"1000",
    "tDate":"9/10/2024"
}