###Testing api calls

###User
###Get New User
GET http://localhost:8001/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzI4MDA4ODE5LCJleHAiOjE3MjgwMDg4Nzl9.lAvJ6pOKoJ7U_gikCAdC7D_4DMYc_jf8fQ4Rv_9P4-4.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzI3MjU4ODE3LCJleHAiOjE3MjcyNTg4Nzd9.n9vfeAV54ijiKzYa1tlpleHVen-C3Hl6vtazczEoE98

### Post New User
POST http://localhost:8001/api/v1/users/login
Content-Type: application/json

{
    
    "email":"a@gmail.com",
    "password":"as"
}




###Transactions